export const accumulatedIncomeSeed = [
  {
    id: 1,
    budgetHead: "End-to-End Testbed on Beyond 5G",
    amountText: "₹50 Lakhs",
    amount: 5000000,
    description:
      "Hardware for Beyond 5G, including NTN, SDRs, UAVs, and underwater communication setups.",
    utilisedAmountLakh: 5.07933,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 2,
    budgetHead: "Dedicated Servers for ECE Department",
    amountText: "₹5 Crores",
    amount: 50000000,
    description:
      "DGX-like and CPU servers for high computational power needs in research.",
    utilisedAmountLakh: 0.59205,
    purchasesFor: "3.8 Cr, (Dr. Saket)",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 3,
    budgetHead: "Distinguished Guests",
    amountText: "₹10 Lakhs/year for 2 years (Total 20 lakhs)",
    amount: 2000000,
    description:
      "Engage international faculty for mentoring and collaborative grant writing.",
    utilisedAmountLakh: 0,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 4,
    budgetHead: "ECE Floor Transformation",
    amountText: "₹3 Lakhs",
    amount: 300000,
    description: "Enhance floor with lab pictures, screens, and video demos.",
    utilisedAmountLakh: 0,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 5,
    budgetHead: "Hosting Conferences",
    amountText: "₹2 Lakhs/year for 2 years (Total 4 lakhs)",
    amount: 400000,
    description: "Hosting academic conferences to improve research visibility.",
    utilisedAmountLakh: 0,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 6,
    budgetHead: "Scholarship for Top Performers",
    amountText: "₹12 Lakhs for 2 years",
    amount: 1200000,
    description: "Retain high-performing students through scholarships.",
    utilisedAmountLakh: 1.51612,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 7,
    budgetHead: "Inviting School Students",
    amountText: "₹2.5 Lakhs for 2 years",
    amount: 250000,
    description:
      "Training modules and challenges for school students to attract bright minds.",
    utilisedAmountLakh: 0,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 8,
    budgetHead: "Industry-Academia Ideathons",
    amountText: "₹15 Lakhs/year for 2 years (Total 30 lakhs)",
    amount: 3000000,
    description:
      "Ideathons to connect industry with academia and improve UG student perception.",
    utilisedAmountLakh: 10.05,
    purchasesFor: "Events of CiPD with ECE; 1.5 for Telecom Shakti",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 9,
    budgetHead: "Digital Whiteboards for Faculty",
    amountText: "₹10 Lakhs",
    amount: 1000000,
    description:
      "Equip offices with digital whiteboards for enhanced discussions and screen-sharing, air-purifiers.",
    utilisedAmountLakh: 3.9,
    purchasesFor: "Panel & Camera",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 10,
    budgetHead: "Embedded Systems Equipment",
    amountText: "₹29 Lakhs",
    amount: 2900000,
    description: "Advanced embedded system boards for teaching and research.",
    utilisedAmountLakh: 1.28634,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
  {
    id: 11,
    budgetHead: "Nanofabrication Consumables",
    amountText: "₹15 Lakhs/year for 2 years (Total 30 lakhs)",
    amount: 3000000,
    description:
      "Contingency budget for consumables and imported items for VLSI labs.",
    utilisedAmountLakh: 0,
    purchasesFor: "",
    invoice: "Not attached",
    invoiceUrl: "",
  },
];

export const expenditureBudgetHeads = [
  "Internal engagements (Refreshment and other related Expenses for department/Centre faculty Meetings, Seminars, official Lunch/ Dinners etc.)",
  "Expenditure on student & faculty recruitment",
  "Provision of support to students of department/centre for Presenting at conferences/events etc. including organizing events",
  "External engagement (Expenditure on Travel and stay of Experts/Visitors for a seminar or otherwise for Interaction and payment of honorarium, Gifts/Mementoes/Souvenirs to Guest/Speakers/faculty and for workshops/Seminars/Conferences etc.)",
  "Consumables & Non-consumables",
  "Industry Day/ECE Day",
  "Department publicity (alumni meet, hackathons/student club activities/ competitions/ IEEE advertisements/ professional videos etc.)",
  "Department development budget",
];

export const expenditureSeed = [
  {
    id: 1,
    head: expenditureBudgetHeads[0],
    budgetLakh: 1.5,
    expensesDescription: "4504 / April 2026 / 8654 / May 2026 / 20444 / May 2026",
    utilizedLakh: 0.34,
    balanceLakh: 1.16,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 34000,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Approved",
  },
  {
    id: 2,
    head: expenditureBudgetHeads[1],
    budgetLakh: 0.5,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 0.5,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 3,
    head: expenditureBudgetHeads[2],
    budgetLakh: 0.68,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 0.68,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 4,
    head: expenditureBudgetHeads[3],
    budgetLakh: 0.5,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 0.5,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 5,
    head: expenditureBudgetHeads[4],
    budgetLakh: 0.5,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 0.5,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 6,
    head: expenditureBudgetHeads[5],
    budgetLakh: 1,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 1,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 7,
    head: expenditureBudgetHeads[6],
    budgetLakh: 0.5,
    expensesDescription: "",
    utilizedLakh: 0,
    balanceLakh: 0.5,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 0,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Pending",
  },
  {
    id: 8,
    head: expenditureBudgetHeads[7],
    budgetLakh: 2.5,
    expensesDescription: "130000 / April 2026 / 9359 / May 2026",
    utilizedLakh: 1.4,
    balanceLakh: 1.1,
    vendor: "ECE Department",
    date: "2026-04-01",
    amount: 140000,
    invoice: "Not attached",
    invoiceUrl: "",
    status: "Approved",
  },
];

export const inventorySeed = [
  {
    id: 1,
    item: "Digital Storage Oscilloscope",
    category: "Lab Equipment",
    quantity: 6,
    location: "ECE Lab 204",
    purchaseDate: "2026-04-18",
    amount: 420000,
    invoice: "tek-scope-invoice.pdf",
  },
  {
    id: 2,
    item: "Soldering Station",
    category: "Tools",
    quantity: 12,
    location: "ECE Workshop",
    purchaseDate: "2026-05-07",
    amount: 48000,
    invoice: "soldering-stations.pdf",
  },
  {
    id: 3,
    item: "FPGA Trainer Kit",
    category: "Teaching Aid",
    quantity: 10,
    location: "Digital Systems Lab",
    purchaseDate: "2026-06-04",
    amount: 310000,
    invoice: "fpga-kits.pdf",
  },
];
